# https://github.com/XiaoMi/soar/blob/dev/doc/config.md
test-dsn:
  addr:     127.0.0.1:3306
  schema:   soar
  user:     root
  password: "root"
  disable:  false

log-output: ""
# log level: [0:Emergency, 1:Alert, 2:Critical, 3:Error, 4:Warning, 5:Notice, 6:Informational, 7:Debug]
log-level: 6

sampling: false
profiling: false
trace: false
explain: false

report-type: "json"

ignore-rules:
  - "COL.011"
rewrite-rules:
  - "delimiter"
  - "orderbynull"
  - "groupbyconst"
  - "dmlorderby"
  - "having"
  - "star2columns"
  - "insertcolumns"
  - "distinctstar"

#blacklist: "soar.blacklist"

allow-online-as-test: false
drop-test-temporary: true
cleanup-test-database: false
only-syntax-check: false
sampling-statistic-target: 100
sampling-condition: ""
delimiter: ";"
max-join-table-count: 5
max-group-by-cols-count: 5
max-distinct-count: 5
max-index-cols-count: 5
max-text-cols-count: 2
max-total-rows: 9999999
max-query-cost: 9999
spaghetti-query-length: 2048
allow-drop-index: false
max-in-count: 10
max-index-bytes-percolumn: 767
max-index-bytes: 3072
allow-charsets:
  - "utf8"
  - "utf8mb4"
allow-collates: []
allow-engines:
  - "innodb"
max-index-count: 10
max-column-count: 40
max-value-count: 100
index-prefix: "idx_"
unique-key-prefix: "uk_"
max-subquery-depth: 5
max-varchar-length: 1024
column-not-allow-type:
  - boolean
  - enum
min-cardinality: 0
explain-sql-report-type: "pretty"
explain-type: "extended"
explain-format: "traditional"
explain-warn-select-type: [""]
explain-warn-access-type:
  - All
explain-max-keys: 3
explain-min-keys: 0
explain-max-rows: 10000
explain-warn-extra:
  - "Using temporary"
  - "Using filesort"
explain-max-filtered: 100.0
explain-warn-scalability:
  - "O(n)"
show-warnings: false
show-last-query-cost: false
list-heuristic-rules: false
list-rewrite-rules: false
list-test-sqls: false
list-report-types: false
max-pretty-sql-length: 2048
# query: ""
# verbose
# dry-run
# report-css: ""
# report-javascript: ""
# report-title: ""
# markdown-extensions: 94
# markdown-html-flags: 0
