name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build

    - name: Test
      run: |
        cd ./internal/app/query
        go test -v service_test.go service.go config.go query.go repository.go -test.run Service_GetConfig
